"""Tests for TsconfigAnalyzer."""

from pathlib import Path

from devai.tsconfig_analyzer import TsconfigAnalyzer, TsconfigFinding


INSECURE_TSCONFIG = """\
{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "strict": false,
    "noImplicitAny": false,
    "strictNullChecks": false,
    "skipLibCheck": true,
    "noEmitOnError": false,
    "allowJs": true,
    "checkJs": false,
    "sourceMap": true,
    "inlineSourceMap": true,
    "suppressImplicitAnyIndexErrors": true,
    "ignoreDeprecations": "5.0",
    "forceConsistentCasingInFileNames": false,
    "api_key": "api_key=hardcoded_secret_value_12345"
  },
  "exclude": ["src/**", "lib/*"]
}
"""

HARDENED_TSCONFIG = """\
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noEmitOnError": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": false,
    "sourceMap": false
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}
"""


class TestTsconfigAnalyzer:
    def test_detects_insecure_tsconfig(self, tmp_path: Path):
        (tmp_path / "tsconfig.json").write_text(INSECURE_TSCONFIG, encoding="utf-8")
        analyzer = TsconfigAnalyzer(str(tmp_path))
        findings = analyzer.analyze()
        kinds = {f.kind for f in findings}
        assert "hardcoded_secret" in kinds
        assert "strict_disabled" in kinds
        assert "no_implicit_any_disabled" in kinds
        assert "strict_null_checks_disabled" in kinds
        assert "skip_lib_check" in kinds
        assert "no_emit_on_error_disabled" in kinds
        assert "allow_js_without_check" in kinds
        assert "source_map_enabled" in kinds
        assert "suppress_index_errors" in kinds
        assert "broad_exclude" in kinds
        assert analyzer.health_score() < 50.0

    def test_hardened_tsconfig_scores_well(self, tmp_path: Path):
        (tmp_path / "tsconfig.json").write_text(HARDENED_TSCONFIG, encoding="utf-8")
        analyzer = TsconfigAnalyzer(str(tmp_path))
        analyzer.analyze()
        assert analyzer.health_score() >= 90.0
        assert analyzer.infos[0].strict is True
        assert analyzer.infos[0].target == "ES2022"

    def test_finds_tsconfig_variants(self, tmp_path: Path):
        (tmp_path / "tsconfig.build.json").write_text(HARDENED_TSCONFIG, encoding="utf-8")
        (tmp_path / "jsconfig.json").write_text(HARDENED_TSCONFIG, encoding="utf-8")
        analyzer = TsconfigAnalyzer(str(tmp_path))
        assert len(analyzer.config_files()) == 2

    def test_no_configs_returns_perfect_score(self, tmp_path: Path):
        analyzer = TsconfigAnalyzer(str(tmp_path))
        assert analyzer.health_score() == 100.0
        assert analyzer.stats.config_files == 0

    def test_finding_format(self):
        finding = TsconfigFinding(
            kind="strict_disabled",
            severity="medium",
            message="strict mode disabled",
            path="tsconfig.json",
            lineno=4,
            line='"strict": false',
        )
        assert "tsconfig.json:4" in finding.format()

    def test_invalid_json(self, tmp_path: Path):
        (tmp_path / "tsconfig.json").write_text("{not json", encoding="utf-8")
        analyzer = TsconfigAnalyzer(str(tmp_path))
        findings = analyzer.analyze()
        assert any(f.kind == "invalid_json" for f in findings)

    def test_generate_hardened_template(self):
        analyzer = TsconfigAnalyzer(".")
        template = analyzer.generate_hardened_template()
        assert '"strict": true' in template
        assert "Generated by DevAI TsconfigAnalyzer" in template

    def test_summary_and_context(self, tmp_path: Path):
        (tmp_path / "tsconfig.json").write_text(HARDENED_TSCONFIG, encoding="utf-8")
        analyzer = TsconfigAnalyzer(str(tmp_path))
        assert "TypeScript:" in analyzer.summary()
        assert "health score" in analyzer.to_context()
