"""Tests for EnvVarAnalyzer."""

from pathlib import Path

from devai.env_vars import EnvVarAnalyzer, EnvVarGap


SETTINGS = """
import os

DATABASE_URL = os.getenv("DATABASE_URL")
DEBUG = os.environ.get("DEBUG", "false")
API_KEY = os.environ["API_KEY"]
"""

ENV_EXAMPLE = """
# Primary database connection
DATABASE_URL=postgres://localhost/app

# Feature flag
DEBUG=

LEGACY_KEY=old
"""

ENV_LOCAL = """
DATABASE_URL=postgres://prod/db
API_KEY=secret
"""


class TestEnvVarAnalyzer:
    def test_parses_env_files(self, tmp_path: Path):
        (tmp_path / ".env.example").write_text(ENV_EXAMPLE, encoding="utf-8")
        (tmp_path / ".env").write_text(ENV_LOCAL, encoding="utf-8")
        (tmp_path / "settings.py").write_text(SETTINGS, encoding="utf-8")

        analyzer = EnvVarAnalyzer(str(tmp_path))
        defs = analyzer.definitions()
        names = {d.name for d in defs}
        assert "DATABASE_URL" in names
        assert "LEGACY_KEY" in names

        refs = analyzer.references()
        ref_names = {r.name for r in refs}
        assert ref_names == {"DATABASE_URL", "DEBUG", "API_KEY"}

    def test_detects_missing_from_example(self, tmp_path: Path):
        (tmp_path / ".env.example").write_text("DATABASE_URL=\n", encoding="utf-8")
        (tmp_path / "settings.py").write_text(
            'import os\nx = os.getenv("API_KEY")\n', encoding="utf-8"
        )

        analyzer = EnvVarAnalyzer(str(tmp_path))
        gaps = analyzer.analyze()
        kinds = {g.kind for g in gaps}
        assert "missing_from_example" in kinds
        missing = next(g for g in gaps if g.kind == "missing_from_example")
        assert missing.name == "API_KEY"
        assert missing.severity == "high"

    def test_detects_unused_in_code(self, tmp_path: Path):
        (tmp_path / ".env.example").write_text("UNUSED_VAR=value\n", encoding="utf-8")
        (tmp_path / "app.py").write_text("x = 1\n", encoding="utf-8")

        analyzer = EnvVarAnalyzer(str(tmp_path))
        gaps = analyzer.analyze()
        assert any(g.kind == "unused_in_code" and g.name == "UNUSED_VAR" for g in gaps)

    def test_detects_empty_value(self, tmp_path: Path):
        (tmp_path / ".env.example").write_text("DEBUG=\n", encoding="utf-8")
        (tmp_path / "app.py").write_text(
            'import os\nflag = os.getenv("DEBUG")\n', encoding="utf-8"
        )

        analyzer = EnvVarAnalyzer(str(tmp_path))
        gaps = analyzer.analyze()
        assert any(g.kind == "empty_value" and g.name == "DEBUG" for g in gaps)

    def test_generate_example(self, tmp_path: Path):
        (tmp_path / "app.py").write_text(
            'import os\nurl = os.getenv("DATABASE_URL")\n', encoding="utf-8"
        )

        analyzer = EnvVarAnalyzer(str(tmp_path))
        example = analyzer.generate_example()
        assert "DATABASE_URL=" in example
        assert "Generated by DevAI" in example

    def test_summary_context_and_health(self, tmp_path: Path):
        (tmp_path / ".env.example").write_text("DATABASE_URL=\n", encoding="utf-8")
        (tmp_path / "app.py").write_text(
            'import os\nurl = os.getenv("DATABASE_URL")\n', encoding="utf-8"
        )

        analyzer = EnvVarAnalyzer(str(tmp_path))
        assert "Env vars:" in analyzer.summary()
        assert "Environment variable analysis" in analyzer.to_context()
        assert 0.0 <= analyzer.health_score() <= 100.0

    def test_gap_format(self):
        gap = EnvVarGap(
            name="API_KEY",
            kind="missing_from_example",
            severity="high",
            message="referenced in code but missing from .env.example",
        )
        assert "API_KEY" in gap.format()
        assert "high" in gap.format()
