"""Tests for GitignoreAnalyzer."""

from pathlib import Path

from devai.gitignore_analyzer import GitignoreAnalyzer, GitignoreGap


PYTHON_GITIGNORE = """
__pycache__/
*.py[cod]
.venv/
.env
*.pem
.DS_Store
"""


class TestGitignoreAnalyzer:
    def test_detects_missing_gitignore(self, tmp_path: Path):
        (tmp_path / "app.py").write_text("x = 1\n", encoding="utf-8")
        analyzer = GitignoreAnalyzer(str(tmp_path))
        gaps = analyzer.analyze()
        assert any(g.kind == "missing_file" for g in gaps)
        assert analyzer.health_score() == 0.0

    def test_counts_covered_patterns(self, tmp_path: Path):
        (tmp_path / ".gitignore").write_text(PYTHON_GITIGNORE, encoding="utf-8")
        (tmp_path / "app.py").write_text("x = 1\n", encoding="utf-8")

        analyzer = GitignoreAnalyzer(str(tmp_path))
        stats = analyzer.stats
        assert stats.has_gitignore is True
        assert stats.covered > 0
        assert stats.patterns > 0

    def test_detects_missing_pattern(self, tmp_path: Path):
        (tmp_path / ".gitignore").write_text("node_modules/\n", encoding="utf-8")
        (tmp_path / "app.py").write_text("x = 1\n", encoding="utf-8")

        analyzer = GitignoreAnalyzer(str(tmp_path))
        gaps = analyzer.analyze()
        missing = [g for g in gaps if g.kind == "missing_pattern"]
        patterns = {g.pattern for g in missing}
        assert ".env" in patterns
        assert "__pycache__/" in patterns

    def test_detects_exposed_env_file(self, tmp_path: Path):
        (tmp_path / ".gitignore").write_text("*.log\n", encoding="utf-8")
        (tmp_path / ".env").write_text("SECRET=abc\n", encoding="utf-8")

        analyzer = GitignoreAnalyzer(str(tmp_path))
        gaps = analyzer.analyze()
        assert any(g.kind == "exposed_file" and g.pattern == ".env" for g in gaps)

    def test_generate_template(self, tmp_path: Path):
        (tmp_path / "app.py").write_text("x = 1\n", encoding="utf-8")

        analyzer = GitignoreAnalyzer(str(tmp_path))
        template = analyzer.generate_template()
        assert "Generated by DevAI" in template
        assert ".env" in template
        assert "__pycache__/" in template

    def test_summary_context_and_health(self, tmp_path: Path):
        (tmp_path / ".gitignore").write_text(PYTHON_GITIGNORE, encoding="utf-8")
        (tmp_path / "app.py").write_text("x = 1\n", encoding="utf-8")

        analyzer = GitignoreAnalyzer(str(tmp_path))
        assert "Gitignore:" in analyzer.summary()
        assert "Gitignore analysis" in analyzer.to_context()
        assert 0.0 <= analyzer.health_score() <= 100.0

    def test_gap_format(self):
        gap = GitignoreGap(
            kind="missing_pattern",
            severity="high",
            pattern=".env",
            message="recommended pattern missing",
        )
        assert ".env" in gap.format()
        assert "high" in gap.format()
