"""Tests for PrecommitAnalyzer."""

from pathlib import Path

from devai.precommit_analyzer import PrecommitAnalyzer, PrecommitFinding


GOOD_CONFIG = """\
default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
"""


class TestPrecommitAnalyzer:
    def test_no_config_returns_empty(self, tmp_path: Path):
        analyzer = PrecommitAnalyzer(str(tmp_path))
        findings = analyzer.analyze()
        assert findings == []
        assert analyzer.health_score() == 100.0
        assert "no config" in analyzer.summary().lower()

    def test_clean_config(self, tmp_path: Path):
        (tmp_path / ".pre-commit-config.yaml").write_text(GOOD_CONFIG, encoding="utf-8")
        analyzer = PrecommitAnalyzer(str(tmp_path))
        findings = analyzer.analyze()
        assert not findings
        stats = analyzer.stats
        assert stats.config_files == 1
        assert stats.repos == 1
        assert stats.hooks == 2
        assert analyzer.health_score() == 100.0

    def test_detects_unpinned_rev(self, tmp_path: Path):
        config = (
            "repos:\n"
            "  - repo: https://github.com/pre-commit/pre-commit-hooks\n"
            "    rev: master\n"
            "    hooks:\n"
            "      - id: trailing-whitespace\n"
        )
        (tmp_path / ".pre-commit-config.yaml").write_text(config, encoding="utf-8")
        analyzer = PrecommitAnalyzer(str(tmp_path))
        findings = analyzer.analyze()
        assert any(f.kind == "unpinned_rev" for f in findings)
        assert any(f.severity == "high" for f in findings)

    def test_detects_mutable_tag_rev(self, tmp_path: Path):
        config = (
            "repos:\n"
            "  - repo: https://github.com/pre-commit/pre-commit-hooks\n"
            "    rev: v4\n"
            "    hooks:\n"
            "      - id: trailing-whitespace\n"
        )
        (tmp_path / ".pre-commit-config.yaml").write_text(config, encoding="utf-8")
        findings = PrecommitAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "mutable_tag_rev" for f in findings)

    def test_detects_local_repo(self, tmp_path: Path):
        config = (
            "repos:\n"
            "  - repo: local\n"
            "    hooks:\n"
            "      - id: custom-hook\n"
            "        name: Custom\n"
            "        entry: python scripts/lint.py\n"
            "        language: python\n"
        )
        (tmp_path / ".pre-commit-config.yaml").write_text(config, encoding="utf-8")
        findings = PrecommitAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "local_repo" for f in findings)

    def test_detects_curl_pipe_shell(self, tmp_path: Path):
        config = (
            "repos:\n"
            "  - repo: local\n"
            "    hooks:\n"
            "      - id: install-tool\n"
            "        entry: curl https://example.com/install.sh | bash\n"
            "        language: system\n"
        )
        (tmp_path / ".pre-commit-config.yaml").write_text(config, encoding="utf-8")
        findings = PrecommitAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "curl_pipe_shell" for f in findings)

    def test_detects_secret_in_config(self, tmp_path: Path):
        config = (
            "repos:\n"
            "  - repo: local\n"
            "    hooks:\n"
            "      - id: deploy\n"
            "        entry: deploy\n"
            "        language: system\n"
            "        env:\n"
            "          API_KEY: 'sk_live_abc123secret'\n"
        )
        (tmp_path / ".pre-commit-config.yaml").write_text(config, encoding="utf-8")
        findings = PrecommitAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "secret_in_config" for f in findings)

    def test_detects_unpinned_additional_dep(self, tmp_path: Path):
        config = (
            "repos:\n"
            "  - repo: https://github.com/pre-commit/mirrors-mypy\n"
            "    rev: v1.14.1\n"
            "    hooks:\n"
            "      - id: mypy\n"
            "        additional_dependencies: [types-requests]\n"
        )
        (tmp_path / ".pre-commit-config.yaml").write_text(config, encoding="utf-8")
        findings = PrecommitAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "unpinned_additional_dep" for f in findings)

    def test_generate_template(self, tmp_path: Path):
        template = PrecommitAnalyzer(str(tmp_path)).generate_hardened_template()
        assert "Generated by DevAI" in template
        assert "default_language_version" in template
        assert "detect-private-key" in template

    def test_summary_context_and_infos(self, tmp_path: Path):
        (tmp_path / ".pre-commit-config.yaml").write_text(GOOD_CONFIG, encoding="utf-8")
        analyzer = PrecommitAnalyzer(str(tmp_path))
        assert "Pre-commit:" in analyzer.summary()
        assert "Pre-commit configuration analysis" in analyzer.to_context()
        assert len(analyzer.infos) == 1
        assert analyzer.infos[0].has_default_language_version is True

    def test_finding_format(self):
        finding = PrecommitFinding(
            kind="unpinned_rev",
            severity="high",
            message="test message",
            path=".pre-commit-config.yaml",
            lineno=5,
        )
        assert "high" in finding.format()
        assert "test message" in finding.format()
