"""Tests for ViteAnalyzer."""

from pathlib import Path

from devai.vite_analyzer import ViteAnalyzer, ViteFinding


INSECURE_VITE_CONFIG = """\
import { defineConfig } from 'vite';

export default defineConfig({
  server: {
    host: true,
    open: true,
    strictPort: false,
    cors: true,
    fs: { allow: ['../', '*'] },
    proxy: {
      '/api': { target: 'http://10.0.0.1:8080' },
    },
    https: { rejectUnauthorized: false },
  },
  build: {
    sourcemap: true,
    minify: false,
  },
  define: {
    API_KEY: 'api_key=hardcoded_secret_value_12345',
  },
  envPrefix: '',
  optimizeDeps: { include: ['*'] },
  ssr: { noExternal: true },
  api_key: 'api_key=hardcoded_secret_value_12345',
});
"""

HARDENED_VITE_CONFIG = """\
import { defineConfig } from 'vite';

export default defineConfig({
  server: {
    host: 'localhost',
    strictPort: true,
    cors: { origin: 'http://localhost:5173' },
    fs: { allow: ['.'] },
  },
  build: {
    sourcemap: false,
    minify: 'esbuild',
  },
  envPrefix: 'VITE_',
});
"""


class TestViteAnalyzer:
    def test_detects_insecure_vite_config(self, tmp_path: Path):
        (tmp_path / "vite.config.ts").write_text(INSECURE_VITE_CONFIG, encoding="utf-8")
        analyzer = ViteAnalyzer(str(tmp_path))
        findings = analyzer.analyze()
        kinds = {f.kind for f in findings}
        assert "hardcoded_secret" in kinds
        assert "host_exposed" in kinds
        assert "cors_open" in kinds
        assert "fs_allow_permissive" in kinds
        assert "proxy_internal" in kinds
        assert "reject_unauthorized_false" in kinds
        assert "sourcemap_enabled" in kinds
        assert "minify_disabled" in kinds
        assert "define_secret" in kinds
        assert "env_prefix_broad" in kinds
        assert "inline_all_deps" in kinds
        assert "ssr_no_external_all" in kinds
        assert "open_browser" in kinds
        assert "strict_port_false" in kinds
        assert analyzer.health_score() < 50.0

    def test_hardened_vite_config_scores_well(self, tmp_path: Path):
        (tmp_path / "vite.config.ts").write_text(HARDENED_VITE_CONFIG, encoding="utf-8")
        analyzer = ViteAnalyzer(str(tmp_path))
        analyzer.analyze()
        assert analyzer.health_score() >= 90.0
        assert analyzer.infos[0].has_server is True
        assert analyzer.infos[0].has_build is True

    def test_finds_vite_config_variants(self, tmp_path: Path):
        (tmp_path / "vite.config.js").write_text(HARDENED_VITE_CONFIG, encoding="utf-8")
        (tmp_path / "vite.config.mts").write_text(HARDENED_VITE_CONFIG, encoding="utf-8")
        analyzer = ViteAnalyzer(str(tmp_path))
        assert len(analyzer.configs()) == 2

    def test_no_configs_returns_perfect_score(self, tmp_path: Path):
        analyzer = ViteAnalyzer(str(tmp_path))
        assert analyzer.health_score() == 100.0
        assert analyzer.stats.configs == 0

    def test_finding_format(self):
        finding = ViteFinding(
            kind="host_exposed",
            severity="medium",
            message="dev server bound to all interfaces",
            path="vite.config.ts",
            lineno=5,
            line="host: true",
        )
        assert "vite.config.ts:5" in finding.format()

    def test_generate_hardened_template(self):
        analyzer = ViteAnalyzer(".")
        template = analyzer.generate_hardened_template()
        assert "host: 'localhost'" in template
        assert "Generated by DevAI ViteAnalyzer" in template

    def test_summary_and_context(self, tmp_path: Path):
        (tmp_path / "vite.config.ts").write_text(HARDENED_VITE_CONFIG, encoding="utf-8")
        analyzer = ViteAnalyzer(str(tmp_path))
        assert "Vite:" in analyzer.summary()
        assert "health score" in analyzer.to_context()

    def test_detects_tls_verification_disabled(self, tmp_path: Path):
        config = "process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';"
        (tmp_path / "vite.config.ts").write_text(config, encoding="utf-8")
        analyzer = ViteAnalyzer(str(tmp_path))
        findings = analyzer.analyze()
        assert any(f.kind == "tls_verification_disabled" for f in findings)

    def test_detects_eval_usage(self, tmp_path: Path):
        config = "eval('console.log(1)');"
        (tmp_path / "vite.config.ts").write_text(config, encoding="utf-8")
        analyzer = ViteAnalyzer(str(tmp_path))
        findings = analyzer.analyze()
        assert any(f.kind == "eval_usage" for f in findings)
