"""Tests for DevAI public API exports."""

import devai


class TestPublicAPI:
    def test_version(self):
        assert devai.__version__ == "3.0.0"

    def test_exports(self):
        expected = {
            "Agent",
            "BatchReviewReport",
            "BatchReviewer",
            "BatchRunner",
            "BenchmarkResult",
            "BenchmarkRunner",
            "BenchmarkSample",
            "CodeBlock",
            "CodeIndexer",
            "CodeSymbol",
            "CONFIG_FILENAMES",
            "CIReporter",
            "CodeAssistant",
            "CodeIssue",
            "CodeProject",
            "CodeReviewResult",
            "ContextSection",
            "CodeSandbox",
            "CoderAgent",
            "ConversationMemory",
            "ConversationStore",
            "DevAI",
            "DevAIConfig",
            "DevApp",
            "DevContext",
            "DevDoctor",
            "DevHooks",
            "SUPPORTED_HOOKS",
            "StreamCollector",
            "StreamResult",
            "DevKit",
            "DevPipeline",
            "DevProgram",
            "DevRuntime",
            "DevSchedule",
            "DevTrace",
            "BudgetExceededError",
            "BudgetedLLMClient",
            "BudgetSnapshot",
            "DevWatcher",
            "DiskCachedLLMClient",
            "TokenBudget",
            "WatchEvent",
            "WatchResult",
            "DevWorkflow",
            "DoctorResult",
            "ProgramComposer",
            "ProgramReport",
            "EmbeddingClient",
            "export_program",
            "export_program_to_file",
            "extract_code_blocks",
            "extract_code_by_language",
            "extract_first_code_block",
            "FileReviewResult",
            "GitContext",
            "HealthChecker",
            "HealthResult",
            "FallbackLLMClient",
            "LLMClient",
            "MockEmbeddingClient",
            "MockLLMClient",
            "PatchResult",
            "PerfIssue",
            "PerfReviewResult",
            "PluginRegistry",
            "ProgramEntry",
            "ProgramLibrary",
            "PromptBuilder",
            "ProgramResult",
            "ProgramStepPlan",
            "ProgramTask",
            "SandboxResult",
            "ScheduleResult",
            "ScheduledJob",
            "SecurityAuditResult",
            "SecurityFinding",
            "TraceEvent",
            "WorkflowResult",
            "WorkflowStepResult",
            "apply_unified_diff",
            "assistant",
            "check_health",
            "config_file_template",
            "cron_matches",
            "extract_diff_from_text",
            "find_config_file",
            "get_preset",
            "interpolate",
            "interpolate_context",
            "list_presets",
            "load_config_file",
            "program_schema",
            "quickstart",
            "run_doctor",
            "validate_cron",
            "__version__",
        }
        assert set(devai.__all__) == expected
        for name in expected:
            assert hasattr(devai, name)
