"""Tests for JenkinsfileAnalyzer."""

from pathlib import Path

from devai.jenkinsfile_analyzer import JenkinsfileAnalyzer


GOOD_PIPELINE = """\
pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                sh 'python -m pytest'
            }
        }
    }
}
"""


class TestJenkinsfileAnalyzer:
    def test_no_jenkinsfile_returns_empty(self, tmp_path: Path):
        analyzer = JenkinsfileAnalyzer(str(tmp_path))
        assert analyzer.analyze() == []
        assert "none found" in analyzer.summary().lower()

    def test_clean_pipeline(self, tmp_path: Path):
        (tmp_path / "Jenkinsfile").write_text(GOOD_PIPELINE, encoding="utf-8")
        analyzer = JenkinsfileAnalyzer(str(tmp_path))
        assert not analyzer.analyze()
        assert analyzer.stats.jenkinsfiles == 1

    def test_detects_hardcoded_credential(self, tmp_path: Path):
        pipeline = "pipeline {\n  environment {\n    API_KEY = 'sk_live_secret12345'\n  }\n}\n"
        (tmp_path / "Jenkinsfile").write_text(pipeline, encoding="utf-8")
        findings = JenkinsfileAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "hardcoded_credential" for f in findings)

    def test_detects_sandbox_disabled(self, tmp_path: Path):
        pipeline = "pipeline {\n  agent any\n  options { disableSandbox(true) }\n}\n"
        (tmp_path / "Jenkinsfile").write_text(pipeline, encoding="utf-8")
        findings = JenkinsfileAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "sandbox_disabled" for f in findings)

    def test_generate_template(self, tmp_path: Path):
        template = JenkinsfileAnalyzer(str(tmp_path)).generate_hardened_template()
        assert "Generated by DevAI" in template
        assert "pipeline" in template
