"""Tests for PipToolsAnalyzer."""

from pathlib import Path

from devai.piptools_analyzer import PipToolsAnalyzer, PipToolsFinding


INSECURE_REQUIREMENTS_IN = """\
# requirements.in with insecure patterns
--index-url http://insecure-pypi.example.com/simple/
--extra-index-url https://deploy:pypi-hardcoded-password@private.pypi.example/simple/
--trusted-host insecure-pypi.example.com
--allow-unsafe
--emit-index-url
requests>=2.0
git+https://user:secret-token@github.com/example/pkg.git@main
"""

INSECURE_COMPILED = """\
#
# This file is autogenerated by pip-compile with Python 3.11
#
--index-url http://insecure-pypi.example.com/simple/
requests
flask>=3.0
"""

INSECURE_PYPROJECT = """\
[project]
name = "demo"
version = "0.1.0"

[tool.pip-tools]
compile-args = ["--allow-unsafe", "--trusted-host", "insecure.example.com"]
sync-command = "curl -s https://install.example.com/setup.sh | bash"
password = "hardcoded-piptools-password"
"""

HARDENED_REQUIREMENTS_IN = """\
requests>=2.31.0
flask>=3.0.0
"""

HARDENED_COMPILED = """\
#
# This file is autogenerated by pip-compile with Python 3.11
#
requests==2.31.0 \\
    --hash=sha256:abc123
flask==3.0.0 \\
    --hash=sha256:def456
"""


class TestPipToolsAnalyzer:
    def test_no_configs_returns_perfect_score(self, tmp_path: Path):
        (tmp_path / "app.py").write_text("x = 1\n", encoding="utf-8")
        analyzer = PipToolsAnalyzer(str(tmp_path))
        assert analyzer.stats.configs == 0
        assert analyzer.health_score() == 100.0

    def test_detects_requirements_in(self, tmp_path: Path):
        (tmp_path / "requirements.in").write_text(HARDENED_REQUIREMENTS_IN, encoding="utf-8")
        (tmp_path / "requirements.txt").write_text(HARDENED_COMPILED, encoding="utf-8")
        analyzer = PipToolsAnalyzer(str(tmp_path))
        assert analyzer.stats.configs >= 1

    def test_detects_insecure_patterns(self, tmp_path: Path):
        (tmp_path / "requirements.in").write_text(INSECURE_REQUIREMENTS_IN, encoding="utf-8")
        (tmp_path / "requirements.txt").write_text(INSECURE_COMPILED, encoding="utf-8")
        (tmp_path / "pyproject.toml").write_text(INSECURE_PYPROJECT, encoding="utf-8")
        analyzer = PipToolsAnalyzer(str(tmp_path))
        findings = analyzer.analyze()
        kinds = {f.kind for f in findings}
        assert "hardcoded_secret" in kinds
        assert "insecure_http" in kinds
        assert "scm_credentials" in kinds
        assert "trusted_host" in kinds
        assert "allow_unsafe" in kinds
        assert "emit_index_url" in kinds
        assert "unpinned_compiled_dep" in kinds
        assert "curl_pipe_shell" in kinds
        assert analyzer.health_score() < 50.0

    def test_hardened_config_scores_well(self, tmp_path: Path):
        (tmp_path / "requirements.in").write_text(HARDENED_REQUIREMENTS_IN, encoding="utf-8")
        (tmp_path / "requirements.txt").write_text(HARDENED_COMPILED, encoding="utf-8")
        analyzer = PipToolsAnalyzer(str(tmp_path))
        assert analyzer.health_score() >= 95.0

    def test_finding_format(self, tmp_path: Path):
        (tmp_path / "requirements.in").write_text(INSECURE_REQUIREMENTS_IN, encoding="utf-8")
        analyzer = PipToolsAnalyzer(str(tmp_path))
        finding = analyzer.analyze()[0]
        assert isinstance(finding, PipToolsFinding)
        assert "[high]" in finding.format() or "[medium]" in finding.format()

    def test_summary_and_context(self, tmp_path: Path):
        (tmp_path / "requirements.in").write_text(INSECURE_REQUIREMENTS_IN, encoding="utf-8")
        analyzer = PipToolsAnalyzer(str(tmp_path))
        assert "Pip-tools configs:" in analyzer.summary()
        context = analyzer.to_context()
        assert "Pip-tools analysis:" in context
        assert "dependencies:" in context

    def test_generate_hardened_config(self, tmp_path: Path):
        analyzer = PipToolsAnalyzer(str(tmp_path))
        config = analyzer.generate_hardened_config()
        assert "requirements.in" in config
        assert "pip-compile" in config

    def test_detects_missing_compiled_output(self, tmp_path: Path):
        (tmp_path / "requirements.in").write_text(HARDENED_REQUIREMENTS_IN, encoding="utf-8")
        analyzer = PipToolsAnalyzer(str(tmp_path))
        kinds = {f.kind for f in analyzer.analyze()}
        assert "missing_compiled_output" in kinds

    def test_facade_piptools_method(self):
        from devai.facade import DevAI

        dev = DevAI.mock()
        analyzer = dev.piptools(".")
        assert isinstance(analyzer, PipToolsAnalyzer)

    def test_ignores_plain_requirements_txt(self, tmp_path: Path):
        (tmp_path / "requirements.txt").write_text("requests==2.31.0\n", encoding="utf-8")
        analyzer = PipToolsAnalyzer(str(tmp_path))
        assert analyzer.stats.configs == 0
