"""Tests for DevAI CI helpers."""

import json

import pytest

from devai import CodeAssistant, CIReporter
from devai.ci import (
    ci_gate,
    format_pr_comment,
    github_actions_annotation,
)
from devai.core import MockLLMClient
from devai.program import DevProgram, ProgramResult


class TestGitHubActions:
    def test_annotation_notice(self):
        line = github_actions_annotation("All good", title="DevAI")
        assert line.startswith("::notice,DevAI::")
        assert "All good" in line

    def test_annotation_with_file_and_line(self):
        line = github_actions_annotation(
            "Issue found",
            title="Security",
            file="src/app.py",
            line=42,
            level="warning",
        )
        assert "warning,Security,src/app.py,42" in line

    def test_invalid_level(self):
        with pytest.raises(ValueError, match="level must be"):
            github_actions_annotation("x", level="info")


class TestFormatPRComment:
    def test_string_content(self):
        comment = format_pr_comment("Review passed", title="CI")
        assert "## CI" in comment
        assert "Review passed" in comment
        assert "Generated by" in comment

    def test_program_results(self):
        results = [
            ProgramResult(name="review", action="review", output="Looks good"),
            ProgramResult(name="security", action="security", output="No issues"),
        ]
        comment = format_pr_comment(results)
        assert "### review" in comment
        assert "### security" in comment


class TestCIGate:
    def test_passes_clean_output(self):
        results = [
            ProgramResult(name="security", action="security", output="No critical issues"),
        ]
        passed, report = ci_gate(results)
        assert passed is True
        assert "Passed" in report

    def test_fails_on_keywords(self):
        results = [
            ProgramResult(
                name="security",
                action="security",
                output="Found a critical SQL injection vulnerability",
            ),
        ]
        passed, report = ci_gate(results)
        assert passed is False
        assert "Failed" in report
        assert "security" in report

    def test_ignores_non_blocking_actions(self):
        results = [
            ProgramResult(name="explain", action="explain", output="critical bug here"),
        ]
        passed, _ = ci_gate(results, block_on=["security"])
        assert passed is True


class TestCIReporter:
    def test_run_program_for_ci(self):
        client = MockLLMClient(responses=["clean review", "no critical issues"])
        assistant = CodeAssistant(client=client)
        reporter = CIReporter(assistant)
        program = DevProgram("ci", assistant).add("review", "review").add("security", "security")
        payload = reporter.run_program_for_ci(program, {"code": "def foo(): pass"})
        assert "pr_comment" in payload
        assert "annotations" in payload
        assert payload["passed"] is True
        assert len(payload["results"]) == 2

    def test_structured_review_for_ci(self):
        review_json = json.dumps(
            {
                "summary": "Solid code",
                "score": 8,
                "issues": [{"severity": "low", "message": "Minor style issue"}],
            }
        )
        client = MockLLMClient(default_response=review_json)
        assistant = CodeAssistant(client=client)
        reporter = CIReporter(assistant)
        result, comment = reporter.review_for_ci("def foo(): pass")
        assert result.score == 8
        assert "## DevAI Report" in comment
