"""Tests for MakefileAnalyzer."""

from pathlib import Path

from devai.makefile_analyzer import MakefileAnalyzer, MakefileFinding


GOOD_MAKEFILE = """\
.PHONY: help install test lint clean

help:
\t@echo "Targets: install test lint clean"

install:
\tpip install -e ".[dev]"

test:
\tpython -m pytest

lint:
\truff check .

clean:
\tfind . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
"""


class TestMakefileAnalyzer:
    def test_no_makefile_returns_empty(self, tmp_path: Path):
        analyzer = MakefileAnalyzer(str(tmp_path))
        findings = analyzer.analyze()
        assert findings == []
        assert analyzer.health_score() == 100.0
        assert "no makefiles" in analyzer.summary().lower()

    def test_clean_makefile(self, tmp_path: Path):
        (tmp_path / "Makefile").write_text(GOOD_MAKEFILE, encoding="utf-8")
        analyzer = MakefileAnalyzer(str(tmp_path))
        findings = analyzer.analyze()
        assert not findings
        stats = analyzer.stats
        assert stats.makefiles == 1
        assert stats.targets >= 5
        assert analyzer.health_score() == 100.0

    def test_detects_curl_pipe_shell(self, tmp_path: Path):
        makefile = (
            "install:\n"
            "\tcurl https://example.com/install.sh | bash\n"
        )
        (tmp_path / "Makefile").write_text(makefile, encoding="utf-8")
        findings = MakefileAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "curl_pipe_shell" for f in findings)
        assert any(f.severity == "high" for f in findings)

    def test_detects_dangerous_rm(self, tmp_path: Path):
        makefile = "clean:\n\trm -rf /\n"
        (tmp_path / "Makefile").write_text(makefile, encoding="utf-8")
        findings = MakefileAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "dangerous_rm" for f in findings)

    def test_detects_sudo(self, tmp_path: Path):
        makefile = "deploy:\n\tsudo systemctl restart app\n"
        (tmp_path / "Makefile").write_text(makefile, encoding="utf-8")
        findings = MakefileAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "sudo_usage" for f in findings)

    def test_detects_eval(self, tmp_path: Path):
        makefile = "run:\n\teval \"$(cat script.sh)\"\n"
        (tmp_path / "Makefile").write_text(makefile, encoding="utf-8")
        findings = MakefileAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "eval_usage" for f in findings)

    def test_detects_secret_in_makefile(self, tmp_path: Path):
        makefile = "deploy:\n\tAPI_KEY=sk_live_abc123secret deploy.sh\n"
        (tmp_path / "Makefile").write_text(makefile, encoding="utf-8")
        findings = MakefileAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "secret_in_makefile" for f in findings)

    def test_detects_chmod_777(self, tmp_path: Path):
        makefile = "setup:\n\tchmod 777 /tmp/app\n"
        (tmp_path / "Makefile").write_text(makefile, encoding="utf-8")
        findings = MakefileAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "chmod_777" for f in findings)

    def test_detects_docker_privileged(self, tmp_path: Path):
        makefile = "run:\n\tdocker run --privileged myimage\n"
        (tmp_path / "Makefile").write_text(makefile, encoding="utf-8")
        findings = MakefileAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "docker_privileged" for f in findings)

    def test_detects_missing_phony(self, tmp_path: Path):
        makefile = "clean:\n\trm -rf build/\n"
        (tmp_path / "Makefile").write_text(makefile, encoding="utf-8")
        findings = MakefileAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "missing_phony" for f in findings)

    def test_generate_template(self, tmp_path: Path):
        template = MakefileAnalyzer(str(tmp_path)).generate_hardened_template()
        assert "Generated by DevAI" in template
        assert ".PHONY:" in template
        assert "pytest" in template

    def test_summary_context_and_infos(self, tmp_path: Path):
        (tmp_path / "Makefile").write_text(GOOD_MAKEFILE, encoding="utf-8")
        analyzer = MakefileAnalyzer(str(tmp_path))
        assert "Makefile:" in analyzer.summary()
        assert "Makefile analysis" in analyzer.to_context()
        assert len(analyzer.infos) == 1
        assert analyzer.infos[0].has_phony_decl is True

    def test_finding_format(self):
        finding = MakefileFinding(
            kind="curl_pipe_shell",
            severity="high",
            message="test message",
            path="Makefile",
            lineno=3,
        )
        assert "high" in finding.format()
        assert "test message" in finding.format()

    def test_finds_mk_suffix(self, tmp_path: Path):
        (tmp_path / "tasks.mk").write_text("help:\n\t@echo help\n", encoding="utf-8")
        analyzer = MakefileAnalyzer(str(tmp_path))
        assert len(analyzer.makefiles()) == 1
