"""Tests for MakefileAnalyzer."""

from pathlib import Path

from devai.makefile_analyzer import MakefileAnalyzer, MakefileFinding


GOOD_MAKEFILE = """\
.PHONY: all clean test install

SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c

all: test

test:
\tpython -m pytest

clean:
\trm -rf build dist .pytest_cache

install:
\tpip install -e .
"""


class TestMakefileAnalyzer:
    def test_no_makefile_returns_empty(self, tmp_path: Path):
        analyzer = MakefileAnalyzer(str(tmp_path))
        findings = analyzer.analyze()
        assert findings == []
        assert analyzer.health_score() == 100.0
        assert "no makefiles" in analyzer.summary().lower()

    def test_clean_makefile(self, tmp_path: Path):
        (tmp_path / "Makefile").write_text(GOOD_MAKEFILE, encoding="utf-8")
        analyzer = MakefileAnalyzer(str(tmp_path))
        findings = analyzer.analyze()
        assert not findings
        stats = analyzer.stats
        assert stats.makefiles == 1
        assert stats.targets >= 4
        assert analyzer.health_score() == 100.0

    def test_detects_curl_pipe_shell(self, tmp_path: Path):
        content = (
            ".PHONY: setup\n"
            "setup:\n"
            "\tcurl https://example.com/install.sh | bash\n"
        )
        (tmp_path / "Makefile").write_text(content, encoding="utf-8")
        findings = MakefileAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "curl_pipe_shell" for f in findings)
        assert any(f.severity == "high" for f in findings)

    def test_detects_dangerous_rm(self, tmp_path: Path):
        content = ".PHONY: clean\nclean:\n\trm -rf /\n"
        (tmp_path / "Makefile").write_text(content, encoding="utf-8")
        findings = MakefileAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "dangerous_rm" for f in findings)

    def test_detects_secret_in_makefile(self, tmp_path: Path):
        content = "API_KEY := sk_live_abc123secret\n"
        (tmp_path / "Makefile").write_text(content, encoding="utf-8")
        findings = MakefileAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "secret_in_makefile" for f in findings)

    def test_detects_sudo(self, tmp_path: Path):
        content = ".PHONY: deploy\ndeploy:\n\tsudo systemctl restart app\n"
        (tmp_path / "Makefile").write_text(content, encoding="utf-8")
        findings = MakefileAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "sudo_usage" for f in findings)

    def test_detects_chmod_777(self, tmp_path: Path):
        content = ".PHONY: perms\nperms:\n\tchmod 777 output/\n"
        (tmp_path / "Makefile").write_text(content, encoding="utf-8")
        findings = MakefileAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "chmod_permissive" for f in findings)

    def test_detects_eval(self, tmp_path: Path):
        content = ".PHONY: run\nrun:\n\teval \"$(CMD)\"\n"
        (tmp_path / "Makefile").write_text(content, encoding="utf-8")
        findings = MakefileAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "eval_usage" for f in findings)

    def test_detects_force_push(self, tmp_path: Path):
        content = ".PHONY: push\npush:\n\tgit push --force origin main\n"
        (tmp_path / "Makefile").write_text(content, encoding="utf-8")
        findings = MakefileAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "force_push" for f in findings)

    def test_detects_latest_docker_tag(self, tmp_path: Path):
        content = ".PHONY: run\nrun:\n\tdocker run python:latest python app.py\n"
        (tmp_path / "Makefile").write_text(content, encoding="utf-8")
        findings = MakefileAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "latest_docker_tag" for f in findings)

    def test_detects_mk_extension(self, tmp_path: Path):
        content = ".PHONY: clean\nclean:\n\trm -rf /\n"
        (tmp_path / "tasks.mk").write_text(content, encoding="utf-8")
        findings = MakefileAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "dangerous_rm" for f in findings)
        assert MakefileAnalyzer(str(tmp_path)).stats.makefiles == 1

    def test_generate_template(self, tmp_path: Path):
        template = MakefileAnalyzer(str(tmp_path)).generate_hardened_template()
        assert "Generated by DevAI" in template
        assert ".PHONY:" in template
        assert "pipefail" in template

    def test_summary_context_and_infos(self, tmp_path: Path):
        (tmp_path / "Makefile").write_text(GOOD_MAKEFILE, encoding="utf-8")
        analyzer = MakefileAnalyzer(str(tmp_path))
        assert "Makefile:" in analyzer.summary()
        assert "Makefile analysis" in analyzer.to_context()
        assert len(analyzer.infos) == 1
        assert analyzer.infos[0].has_phony is True

    def test_finding_format(self):
        finding = MakefileFinding(
            kind="dangerous_rm",
            severity="high",
            message="test message",
            path="Makefile",
            lineno=5,
        )
        assert "high" in finding.format()
        assert "test message" in finding.format()
