"""Tests for BitbucketPipelinesAnalyzer."""

from pathlib import Path

from devai.bitbucket_pipelines_analyzer import BitbucketPipelinesAnalyzer


GOOD_CONFIG = """\
image: python:3.12-slim
pipelines:
  default:
    - step:
        name: Test
        script:
          - python -m pytest
"""


class TestBitbucketPipelinesAnalyzer:
    def test_no_config_returns_empty(self, tmp_path: Path):
        analyzer = BitbucketPipelinesAnalyzer(str(tmp_path))
        assert analyzer.analyze() == []
        assert "no config" in analyzer.summary().lower()

    def test_clean_config(self, tmp_path: Path):
        (tmp_path / "bitbucket-pipelines.yml").write_text(GOOD_CONFIG, encoding="utf-8")
        analyzer = BitbucketPipelinesAnalyzer(str(tmp_path))
        assert not analyzer.analyze()
        assert analyzer.stats.config_files == 1

    def test_detects_unpinned_pipe(self, tmp_path: Path):
        config = (
            "pipelines:\n"
            "  default:\n"
            "    - step:\n"
            "        script:\n"
            "          - pipe: atlassian/aws-s3-deploy:main\n"
        )
        (tmp_path / "bitbucket-pipelines.yml").write_text(config, encoding="utf-8")
        findings = BitbucketPipelinesAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "unpinned_pipe" for f in findings)

    def test_detects_latest_image(self, tmp_path: Path):
        config = "image: node:latest\npipelines:\n  default:\n    - step:\n        script:\n          - echo ok\n"
        (tmp_path / "bitbucket-pipelines.yml").write_text(config, encoding="utf-8")
        findings = BitbucketPipelinesAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "latest_image" for f in findings)

    def test_generate_template(self, tmp_path: Path):
        template = BitbucketPipelinesAnalyzer(str(tmp_path)).generate_hardened_template()
        assert "Generated by DevAI" in template
        assert "pipelines:" in template
