"""Tests for K8sAnalyzer."""

from pathlib import Path

from devai.kubernetes_analyzer import K8sAnalyzer


GOOD_DEPLOYMENT = """\
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: app
          image: myapp:1.0.0
          securityContext:
            allowPrivilegeEscalation: false
"""


class TestK8sAnalyzer:
    def test_no_manifests_returns_empty(self, tmp_path: Path):
        analyzer = K8sAnalyzer(str(tmp_path))
        assert analyzer.analyze() == []
        assert "no manifests" in analyzer.summary().lower()

    def test_clean_manifest(self, tmp_path: Path):
        k8s = tmp_path / "k8s"
        k8s.mkdir()
        (k8s / "deployment.yaml").write_text(GOOD_DEPLOYMENT, encoding="utf-8")
        analyzer = K8sAnalyzer(str(tmp_path))
        assert not analyzer.analyze()
        assert analyzer.stats.manifests == 1

    def test_detects_privileged(self, tmp_path: Path):
        manifest = (
            "apiVersion: v1\n"
            "kind: Pod\n"
            "metadata:\n"
            "  name: bad\n"
            "spec:\n"
            "  containers:\n"
            "    - name: app\n"
            "      image: myapp:1.0.0\n"
            "      securityContext:\n"
            "        privileged: true\n"
        )
        k8s = tmp_path / "kubernetes"
        k8s.mkdir()
        (k8s / "pod.yaml").write_text(manifest, encoding="utf-8")
        findings = K8sAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "privileged" for f in findings)

    def test_detects_latest_image(self, tmp_path: Path):
        manifest = (
            "apiVersion: apps/v1\n"
            "kind: Deployment\n"
            "metadata:\n"
            "  name: app\n"
            "spec:\n"
            "  template:\n"
            "    spec:\n"
            "      containers:\n"
            "        - name: app\n"
            "          image: myapp:latest\n"
        )
        manifests = tmp_path / "manifests"
        manifests.mkdir()
        (manifests / "deployment.yml").write_text(manifest, encoding="utf-8")
        findings = K8sAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "latest_image" for f in findings)

    def test_detects_host_network(self, tmp_path: Path):
        manifest = (
            "apiVersion: v1\n"
            "kind: Pod\n"
            "metadata:\n"
            "  name: net\n"
            "spec:\n"
            "  hostNetwork: true\n"
            "  containers:\n"
            "    - name: app\n"
            "      image: myapp:1.0.0\n"
        )
        k8s = tmp_path / "k8s"
        k8s.mkdir()
        (k8s / "pod.yaml").write_text(manifest, encoding="utf-8")
        findings = K8sAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "host_network" for f in findings)

    def test_generate_template(self, tmp_path: Path):
        template = K8sAnalyzer(str(tmp_path)).generate_hardened_template()
        assert "Generated by DevAI" in template
        assert "runAsNonRoot: true" in template
