"""Tests for CircleCIAnalyzer."""

from pathlib import Path

from devai.circleci_analyzer import CircleCIAnalyzer


GOOD_CONFIG = """\
version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: python -m pytest
"""


class TestCircleCIAnalyzer:
    def test_no_config_returns_empty(self, tmp_path: Path):
        analyzer = CircleCIAnalyzer(str(tmp_path))
        assert analyzer.analyze() == []
        assert "no config" in analyzer.summary().lower()

    def test_clean_config(self, tmp_path: Path):
        circleci = tmp_path / ".circleci"
        circleci.mkdir()
        (circleci / "config.yml").write_text(GOOD_CONFIG, encoding="utf-8")
        analyzer = CircleCIAnalyzer(str(tmp_path))
        assert not analyzer.analyze()
        assert analyzer.stats.config_files == 1

    def test_detects_unpinned_orb(self, tmp_path: Path):
        config = (
            "version: 2.1\n"
            "orbs:\n"
            "  python: circleci/python@main\n"
            "jobs:\n"
            "  test:\n"
            "    steps:\n"
            "      - checkout\n"
        )
        circleci = tmp_path / ".circleci"
        circleci.mkdir()
        (circleci / "config.yml").write_text(config, encoding="utf-8")
        findings = CircleCIAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "unpinned_orb" for f in findings)

    def test_detects_latest_image(self, tmp_path: Path):
        config = (
            "version: 2\n"
            "jobs:\n"
            "  test:\n"
            "    docker:\n"
            "      - image: node:latest\n"
        )
        circleci = tmp_path / ".circleci"
        circleci.mkdir()
        (circleci / "config.yml").write_text(config, encoding="utf-8")
        findings = CircleCIAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "latest_image" for f in findings)

    def test_generate_template(self, tmp_path: Path):
        template = CircleCIAnalyzer(str(tmp_path)).generate_hardened_template()
        assert "Generated by DevAI" in template
        assert "version: 2.1" in template
