"""Tests for KubernetesAnalyzer."""

from pathlib import Path

from devai.kubernetes_analyzer import KubernetesAnalyzer, KubernetesFinding


GOOD_DEPLOYMENT = """\
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: app
          image: ghcr.io/example/app:1.0.0
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: database-url
"""


class TestKubernetesAnalyzer:
    def test_no_manifests_returns_empty(self, tmp_path: Path):
        analyzer = KubernetesAnalyzer(str(tmp_path))
        findings = analyzer.analyze()
        assert findings == []
        assert analyzer.health_score() == 100.0
        assert "no manifests" in analyzer.summary().lower()

    def test_clean_deployment(self, tmp_path: Path):
        k8s = tmp_path / "k8s"
        k8s.mkdir()
        (k8s / "deployment.yaml").write_text(GOOD_DEPLOYMENT, encoding="utf-8")
        analyzer = KubernetesAnalyzer(str(tmp_path))
        findings = analyzer.analyze()
        assert not findings
        stats = analyzer.stats
        assert stats.manifests == 1
        assert analyzer.health_score() == 100.0

    def test_detects_privileged(self, tmp_path: Path):
        manifest = GOOD_DEPLOYMENT.replace(
            "allowPrivilegeEscalation: false",
            "allowPrivilegeEscalation: true\n            privileged: true",
        )
        k8s = tmp_path / "k8s"
        k8s.mkdir()
        (k8s / "deployment.yaml").write_text(manifest, encoding="utf-8")
        findings = KubernetesAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "privileged" for f in findings)

    def test_detects_latest_tag(self, tmp_path: Path):
        manifest = GOOD_DEPLOYMENT.replace("app:1.0.0", "app:latest")
        k8s = tmp_path / "k8s"
        k8s.mkdir()
        (k8s / "deployment.yaml").write_text(manifest, encoding="utf-8")
        findings = KubernetesAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "latest_image_tag" for f in findings)

    def test_detects_host_network(self, tmp_path: Path):
        manifest = GOOD_DEPLOYMENT.replace(
            "securityContext:",
            "hostNetwork: true\n      securityContext:",
            1,
        )
        k8s = tmp_path / "k8s"
        k8s.mkdir()
        (k8s / "deployment.yaml").write_text(manifest, encoding="utf-8")
        findings = KubernetesAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "host_network" for f in findings)

    def test_detects_run_as_root(self, tmp_path: Path):
        manifest = GOOD_DEPLOYMENT.replace("runAsUser: 10001", "runAsUser: 0")
        k8s = tmp_path / "k8s"
        k8s.mkdir()
        (k8s / "deployment.yaml").write_text(manifest, encoding="utf-8")
        findings = KubernetesAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "run_as_root" for f in findings)

    def test_detects_plain_secret(self, tmp_path: Path):
        manifest = GOOD_DEPLOYMENT + "\n  password: 'supersecretpassword'\n"
        k8s = tmp_path / "k8s"
        k8s.mkdir()
        (k8s / "deployment.yaml").write_text(manifest, encoding="utf-8")
        findings = KubernetesAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "plain_secret_value" for f in findings)

    def test_generate_template(self, tmp_path: Path):
        template = KubernetesAnalyzer(str(tmp_path)).generate_hardened_template()
        assert "Generated by DevAI" in template
        assert "runAsNonRoot: true" in template

    def test_summary_context_and_infos(self, tmp_path: Path):
        k8s = tmp_path / "k8s"
        k8s.mkdir()
        (k8s / "deployment.yaml").write_text(GOOD_DEPLOYMENT, encoding="utf-8")
        analyzer = KubernetesAnalyzer(str(tmp_path))
        assert "Kubernetes:" in analyzer.summary()
        assert "Kubernetes manifest analysis" in analyzer.to_context()
        assert len(analyzer.infos) == 1

    def test_finding_format(self):
        finding = KubernetesFinding(
            kind="privileged",
            severity="high",
            message="test message",
            path="k8s/deployment.yaml",
            lineno=10,
            resource="Deployment/app",
        )
        assert "high" in finding.format()
        assert "Deployment/app" in finding.format()
