"""Tests for GitLabCIAnalyzer."""

from pathlib import Path

from devai.gitlab_ci_analyzer import GitLabCIAnalyzer, GitLabCIFinding


GOOD_CONFIG = """\
stages:
  - test

test:
  stage: test
  image: python:3.12-slim
  script:
    - pip install -e ".[dev]"
    - python -m pytest
"""


class TestGitLabCIAnalyzer:
    def test_no_config_returns_empty(self, tmp_path: Path):
        analyzer = GitLabCIAnalyzer(str(tmp_path))
        findings = analyzer.analyze()
        assert findings == []
        assert analyzer.health_score() == 100.0
        assert "no config" in analyzer.summary().lower()

    def test_clean_config(self, tmp_path: Path):
        (tmp_path / ".gitlab-ci.yml").write_text(GOOD_CONFIG, encoding="utf-8")
        analyzer = GitLabCIAnalyzer(str(tmp_path))
        findings = analyzer.analyze()
        assert not findings
        assert analyzer.stats.config_files == 1
        assert analyzer.health_score() == 100.0

    def test_detects_latest_image(self, tmp_path: Path):
        config = "test:\n  image: node:latest\n  script:\n    - npm test\n"
        (tmp_path / ".gitlab-ci.yml").write_text(config, encoding="utf-8")
        findings = GitLabCIAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "latest_image" for f in findings)

    def test_detects_unpinned_ref(self, tmp_path: Path):
        config = (
            "include:\n"
            "  - project: group/ci-templates\n"
            "    ref: main\n"
            "    file: /ci/test.yml\n"
        )
        (tmp_path / ".gitlab-ci.yml").write_text(config, encoding="utf-8")
        findings = GitLabCIAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "unpinned_ref" for f in findings)

    def test_detects_curl_pipe_shell(self, tmp_path: Path):
        config = "test:\n  script:\n    - curl https://example.com/install.sh | bash\n"
        (tmp_path / ".gitlab-ci.yml").write_text(config, encoding="utf-8")
        findings = GitLabCIAnalyzer(str(tmp_path)).analyze()
        assert any(f.kind == "curl_pipe_shell" for f in findings)

    def test_generate_template(self, tmp_path: Path):
        template = GitLabCIAnalyzer(str(tmp_path)).generate_hardened_template()
        assert "Generated by DevAI" in template
        assert "stages:" in template

    def test_finding_format(self):
        finding = GitLabCIFinding(
            kind="unpinned_ref",
            severity="high",
            message="test message",
            path=".gitlab-ci.yml",
            lineno=3,
        )
        assert "high" in finding.format()
        assert "test message" in finding.format()
