"""CI/CD report helpers for GitHub Actions and pull request comments."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any

from devai.assistant import CodeAssistant
from devai.schemas import CodeReviewResult, SecurityAuditResult


@dataclass
class CIReport:
    """Structured CI report from DevAI analysis."""

    title: str
    summary: str
    sections: list[dict[str, str]] = field(default_factory=list)
    passed: bool = True
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_markdown(self) -> str:
        """Render the report as GitHub-flavored markdown."""
        status = "✅ Passed" if self.passed else "❌ Failed"
        lines = [f"## {self.title}", "", f"**Status:** {status}", "", self.summary, ""]
        for section in self.sections:
            lines.append(f"### {section['title']}")
            lines.append("")
            lines.append(section["body"])
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def to_github_comment(self) -> str:
        """Format as a PR comment with DevAI footer."""
        body = self.to_markdown()
        return f"{body}\n---\n*Generated by [DevAI](https://github.com/Kkkppmm/-agent-rebuild-everything-with-new-code-and-bug-fixes-and-69-4y)*"

    def to_actions_annotations(self) -> list[dict[str, str]]:
        """Convert findings to GitHub Actions annotation objects."""
        annotations: list[dict[str, str]] = []
        for section in self.sections:
            level = section.get("level", "notice")
            if level not in ("notice", "warning", "error"):
                level = "notice"
            annotations.append(
                {
                    "annotation_level": level,
                    "title": section["title"],
                    "message": section.get("message", section["body"][:500]),
                    "path": section.get("path", ""),
                    "start_line": str(section.get("line", 1)),
                }
            )
        return annotations

    def to_json(self) -> str:
        """Serialize the report to JSON."""
        return json.dumps(
            {
                "title": self.title,
                "summary": self.summary,
                "sections": self.sections,
                "passed": self.passed,
                "metadata": self.metadata,
            },
            indent=2,
        )


class CIReporter:
    """Generate CI reports for code review, security, and diff analysis."""

    def __init__(self, assistant: CodeAssistant) -> None:
        self.assistant = assistant

    def review_diff(self, diff: str, *, title: str = "DevAI Diff Review") -> CIReport:
        """Review a git diff and produce a CI report."""
        review = self.assistant.review_diff(diff)
        lowered = review.lower()
        blockers = (
            "critical issue",
            "critical bug",
            "critical vulnerability",
            "blocker",
            "must fix",
            "do not merge",
        )
        passed = not any(phrase in lowered for phrase in blockers)
        return CIReport(
            title=title,
            summary="Automated diff review completed.",
            sections=[{"title": "Diff Review", "body": review, "level": "warning" if not passed else "notice"}],
            passed=passed,
            metadata={"type": "diff_review"},
        )

    def security_gate(self, code: str, *, title: str = "DevAI Security Gate") -> CIReport:
        """Run a structured security audit as a CI gate."""
        result: SecurityAuditResult = self.assistant.structured_security(code)
        passed = result.risk_level in ("low", "medium")
        sections = [
            {
                "title": f"Security ({result.risk_level})",
                "body": result.summary,
                "level": "error" if not passed else "notice",
            }
        ]
        for finding in result.findings:
            sections.append(
                {
                    "title": f"[{finding.severity}] {finding.category}",
                    "body": f"{finding.description}\n\n**Remediation:** {finding.remediation or 'N/A'}",
                    "level": "error" if finding.severity in ("high", "critical") else "warning",
                }
            )
        return CIReport(
            title=title,
            summary=result.summary,
            sections=sections,
            passed=passed,
            metadata={"type": "security_gate", "risk_level": result.risk_level},
        )

    def code_review_gate(self, code: str, *, title: str = "DevAI Code Review") -> CIReport:
        """Run a structured code review as a CI gate."""
        result: CodeReviewResult = self.assistant.structured_review(code)
        passed = result.score >= 7 and not any(
            i.severity in ("high", "critical") for i in result.issues
        )
        sections: list[dict[str, str]] = [
            {
                "title": f"Review (score: {result.score}/10)",
                "body": result.summary,
                "level": "error" if not passed else "notice",
            }
        ]
        for issue in result.issues:
            sections.append(
                {
                    "title": f"[{issue.severity}] Line {issue.line or '?'}",
                    "body": f"{issue.message}\n\n**Suggestion:** {issue.suggestion or 'N/A'}",
                    "level": "error" if issue.severity in ("high", "critical") else "warning",
                    "line": str(issue.line or 1),
                }
            )
        return CIReport(
            title=title,
            summary=result.summary,
            sections=sections,
            passed=passed,
            metadata={"type": "code_review_gate", "score": result.score},
        )

    def full_ci_gate(self, code: str, diff: str | None = None) -> CIReport:
        """Run review + security gates and combine into one report."""
        review_report = self.code_review_gate(code, title="Code Review")
        security_report = self.security_gate(code, title="Security Audit")
        sections = review_report.sections + security_report.sections
        if diff:
            diff_report = self.review_diff(diff, title="Diff Review")
            sections.extend(diff_report.sections)
        passed = review_report.passed and security_report.passed
        return CIReport(
            title="DevAI CI Gate",
            summary=f"Review score: {review_report.metadata.get('score', 'N/A')}/10. "
            f"Security risk: {security_report.metadata.get('risk_level', 'unknown')}.",
            sections=sections,
            passed=passed,
            metadata={"type": "full_ci_gate"},
        )


def write_github_output(report: CIReport, *, output_file: str | None = None) -> None:
    """Write report fields to GITHUB_OUTPUT for Actions workflows."""
    import os

    path = output_file or os.environ.get("GITHUB_OUTPUT")
    if not path:
        return
    with open(path, "a", encoding="utf-8") as f:
        f.write(f"devai_passed={str(report.passed).lower()}\n")
        f.write(f"devai_summary={report.summary.replace(chr(10), ' ')}\n")
