"""CI/CD helpers for DevAI — GitHub PR comments and Actions annotations."""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from devai.program import ProgramResult


@dataclass
class CIAnnotation:
    """A single GitHub Actions workflow annotation."""

    level: str
    message: str
    file: str | None = None
    line: int | None = None
    title: str | None = None

    def to_actions_line(self) -> str:
        """Format as a GitHub Actions workflow command."""
        parts: list[str] = []
        if self.file:
            parts.append(f"file={self.file}")
        if self.line is not None:
            parts.append(f"line={self.line}")
        if self.title:
            parts.append(f"title={self.title}")
        suffix = ",".join(parts)
        body = f"::{self.level} {suffix}::{self.message}" if suffix else f"::{self.level}::{self.message}"
        return body


def format_pr_comment(
    results: list[ProgramResult],
    *,
    title: str = "DevAI CI Report",
    program_name: str | None = None,
) -> str:
    """Format program results as a GitHub pull request comment."""
    header = f"## {title}"
    if program_name:
        header += f" — `{program_name}`"
    parts = [header, ""]
    for result in results:
        parts.append(f"### {result.name} (`{result.action}`)")
        parts.append("")
        parts.append(result.output.strip())
        parts.append("")
    parts.append("---")
    parts.append("*Generated by [DevAI](https://github.com/Kkkppmm/-agent-rebuild-everything-with-new-code-and-bug-fixes-and-69-4y)*")
    return "\n".join(parts)


def format_actions_summary(
    results: list[ProgramResult],
    *,
    title: str = "DevAI CI Summary",
) -> str:
    """Format program results for GitHub Actions step summary (markdown)."""
    lines = [f"# {title}", ""]
    for result in results:
        lines.append(f"## {result.name} ({result.action})")
        lines.append("")
        lines.append(result.output.strip())
        lines.append("")
    return "\n".join(lines)


def extract_annotations(
    results: list[ProgramResult],
    *,
    default_level: str = "warning",
) -> list[CIAnnotation]:
    """Extract GitHub Actions annotations from program output.

    Looks for patterns like ``file.py:42: error message`` or
    ``[security] path/to/file.py:10 - issue description``.
    """
    annotations: list[CIAnnotation] = []
    pattern = re.compile(
        r"(?:\[(?P<tag>[^\]]+)\]\s*)?"
        r"(?P<file>[^\s:]+\.[a-zA-Z0-9]+)"
        r"(?::(?P<line>\d+))?"
        r"\s*[-:]\s*(?P<message>.+)"
    )
    for result in results:
        for line in result.output.splitlines():
            match = pattern.search(line.strip())
            if not match:
                continue
            level = default_level
            tag = (match.group("tag") or "").lower()
            if tag in {"error", "critical", "high"}:
                level = "error"
            elif tag in {"info", "note", "low"}:
                level = "notice"
            line_no = int(match.group("line")) if match.group("line") else None
            annotations.append(
                CIAnnotation(
                    level=level,
                    message=match.group("message").strip(),
                    file=match.group("file"),
                    line=line_no,
                    title=result.name,
                )
            )
    return annotations


def format_actions_annotations(annotations: list[CIAnnotation]) -> str:
    """Render annotations as GitHub Actions workflow commands."""
    return "\n".join(a.to_actions_line() for a in annotations)


def ci_gate_passed(
    results: list[ProgramResult],
    *,
    fail_keywords: tuple[str, ...] = ("critical", "vulnerability", "must fix", "blocker"),
) -> bool:
    """Return False if any result output contains blocking keywords."""
    combined = " ".join(r.output.lower() for r in results)
    return not any(keyword in combined for keyword in fail_keywords)


def write_step_summary(markdown: str, *, path: str = "") -> None:
    """Write markdown to the GitHub Actions step summary file."""
    summary_path = path or __import__("os").environ.get("GITHUB_STEP_SUMMARY", "")
    if not summary_path:
        return
    with open(summary_path, "a", encoding="utf-8") as handle:
        handle.write(markdown)
        if not markdown.endswith("\n"):
            handle.write("\n")
