"""CI/CD helpers for integrating DevAI into pipelines."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from devai.assistant import CodeAssistant
from devai.program import DevProgram, ProgramResult
from devai.schemas import CodeReviewResult, SecurityAuditResult


def github_actions_annotation(
    message: str,
    *,
    title: str = "DevAI",
    file: str | None = None,
    line: int | None = None,
    level: str = "notice",
) -> str:
    """Format a message as a GitHub Actions workflow command annotation."""
    valid_levels = {"notice", "warning", "error"}
    if level not in valid_levels:
        raise ValueError(f"level must be one of {valid_levels}")

    parts = [level, title.replace("%", "%25").replace("\n", "%0A").replace("\r", "%0A")]
    if file:
        parts.append(file.replace("%", "%25"))
    if line is not None:
        parts.append(str(line))

    encoded_message = (
        message.replace("%", "%25")
        .replace("\r\n", "%0A")
        .replace("\n", "%0A")
        .replace("\r", "%0A")
    )
    return f"::{','.join(parts)}::{encoded_message}"


def format_pr_comment(
    content: str | list[ProgramResult],
    *,
    title: str = "DevAI Report",
) -> str:
    """Format program results or text as a GitHub PR comment."""
    if isinstance(content, str):
        body = content
    else:
        sections = [
            f"### {result.name} (`{result.action}`)\n\n{result.output}"
            for result in content
        ]
        body = "\n\n---\n\n".join(sections)

    return f"## {title}\n\n{body}\n\n---\n*Generated by [DevAI](https://github.com/Kkkppmm/-agent-rebuild-everything-with-new-code-and-bug-fixes-and-69-4y)*"


def ci_gate(
    results: list[ProgramResult],
    *,
    block_on: list[str] | None = None,
    keywords: list[str] | None = None,
) -> tuple[bool, str]:
    """Evaluate whether CI should pass based on program output.

    Returns (passed, markdown_report).
    """
    block_actions = set(block_on or ["security"])
    failure_keywords = [k.lower() for k in (keywords or ["critical", "high severity", "must fix"])]

    failures: list[str] = []
    for result in results:
        if result.action not in block_actions:
            continue
        lowered = result.output.lower()
        matched: list[str] = []
        for kw in failure_keywords:
            start = 0
            while True:
                idx = lowered.find(kw, start)
                if idx == -1:
                    break
                prefix = lowered[max(0, idx - 4) : idx].strip()
                if prefix != "no":
                    matched.append(kw)
                    break
                start = idx + len(kw)
        if matched:
            failures.append(
                f"- **{result.name}** (`{result.action}`): matched {', '.join(matched)}"
            )

    passed = not failures
    status = "✅ Passed" if passed else "❌ Failed"
    report_lines = [f"## CI Gate: {status}", ""]
    if failures:
        report_lines.append("Blocking issues detected:")
        report_lines.extend(failures)
    else:
        report_lines.append("No blocking issues detected.")
    return passed, "\n".join(report_lines)


@dataclass
class CIReporter:
    """Run DevAI workflows and produce CI-ready output."""

    assistant: CodeAssistant

    def review_for_ci(self, code: str) -> tuple[CodeReviewResult, str]:
        """Run structured review and return model + PR comment."""
        result = self.assistant.structured_review(code)
        comment = self._format_structured_review(result)
        return result, comment

    def security_for_ci(self, code: str) -> tuple[SecurityAuditResult, str]:
        """Run structured security audit and return model + PR comment."""
        result = self.assistant.structured_security(code)
        comment = self._format_security_audit(result)
        return result, comment

    def run_program_for_ci(
        self,
        program: DevProgram | str,
        context: dict[str, str],
        *,
        gate: bool = True,
    ) -> dict[str, Any]:
        """Run a program and return CI artifacts."""
        if isinstance(program, str):
            from devai.presets import get_preset

            program = get_preset(program, self.assistant)

        results = program.run(context)
        payload: dict[str, Any] = {
            "results": results,
            "pr_comment": format_pr_comment(results),
            "annotations": self._results_to_annotations(results),
        }
        if gate:
            passed, gate_report = ci_gate(results)
            payload["passed"] = passed
            payload["gate_report"] = gate_report
        return payload

    def _format_structured_review(self, result: CodeReviewResult) -> str:
        issues = "\n".join(
            f"- **[{issue.severity}]** {issue.message}" for issue in result.issues
        ) or "- No issues found"
        return format_pr_comment(
            f"**Score:** {result.score}/10\n\n"
            f"**Summary:** {result.summary}\n\n"
            f"**Issues:**\n{issues}"
        )

    def _format_security_audit(self, result: SecurityAuditResult) -> str:
        findings = "\n".join(
            f"- **[{f.severity}]** {f.category}: {f.description}" for f in result.findings
        ) or "- No findings"
        return format_pr_comment(
            f"**Risk Level:** {result.risk_level}\n\n"
            f"**Summary:** {result.summary}\n\n"
            f"**Findings:**\n{findings}"
        )

    def _results_to_annotations(self, results: list[ProgramResult]) -> list[str]:
        annotations: list[str] = []
        for result in results:
            level = "warning" if result.action in {"security", "performance"} else "notice"
            summary = result.output[:500].replace("\n", " ")
            annotations.append(
                github_actions_annotation(
                    f"{result.name}: {summary}",
                    title=f"DevAI {result.action}",
                    level=level,
                )
            )
        return annotations
