"""Export DevProgram definitions to standalone Python scripts."""

from __future__ import annotations

import json
import textwrap
from pathlib import Path

from devai.program import DevProgram


def export_program(
    program: DevProgram,
    *,
    use_mock: bool = False,
    provider: str = "openai",
    model: str | None = None,
) -> str:
    """Generate a standalone Python script from a DevProgram.

    The exported script can be run without the original JSON/YAML file.
  It bootstraps DevRuntime, loads context from CLI args, and prints results.
    """
    program_data = program.to_dict()
    program_json = json.dumps(program_data, indent=2)
    provider_literal = json.dumps(provider)
    model_literal = "None" if model is None else json.dumps(model)
    use_mock_literal = "True" if use_mock else "False"

    template = f'''\
#!/usr/bin/env python3
"""Standalone script generated by DevAI from program: {program.name}"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


PROGRAM = json.loads({program_json!r})


def _read_input(value: str) -> str:
    path = Path(value)
    if path.is_file():
        return path.read_text(encoding="utf-8")
    return value


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run DevAI program: {program.name}")
    parser.add_argument("code", nargs="?", help="Code string or file path")
    parser.add_argument("--diff", help="Diff string or file path")
    parser.add_argument(
        "--context",
        action="append",
        metavar="KEY=VALUE",
        help="Additional context variables",
    )
    parser.add_argument("--mock", action="store_true", help="Use mock LLM client")
    parser.add_argument("--json", action="store_true", help="Output results as JSON")
    args = parser.parse_args(argv)

    from devai import DevProgram, DevRuntime

    use_mock = args.mock or {use_mock_literal}
    runtime = DevRuntime.create(
        provider="mock" if use_mock else {provider_literal},
        model={model_literal},
        use_mock=use_mock,
    )
    program = DevProgram.from_dict(PROGRAM, runtime.assistant)

    context: dict[str, str] = {{}}
    if args.code:
        context["code"] = _read_input(args.code)
    if args.diff:
        context["diff"] = _read_input(args.diff)
    if args.context:
        for pair in args.context:
            key, _, value = pair.partition("=")
            context[key] = value

    results = program.run(context)
    if args.json:
        payload = [
            {{"name": r.name, "action": r.action, "output": r.output}}
            for r in results
        ]
        print(json.dumps(payload, indent=2))
    else:
        print(program.run_and_summarize(context))
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''
    return textwrap.dedent(template)


def export_program_to_file(
    program: DevProgram,
    path: str | Path,
    *,
    use_mock: bool = False,
    provider: str = "openai",
    model: str | None = None,
) -> Path:
    """Write an exported program script to disk."""
    path = Path(path)
    path.write_text(
        export_program(program, use_mock=use_mock, provider=provider, model=model),
        encoding="utf-8",
    )
    path.chmod(0o755)
    return path
