"""PipToolsAnalyzer — audit pip-tools requirements.in, compiled requirements.txt, and pyproject.toml for security and build hardening."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

PIPTOOLS_IN_NAMES = (
    "requirements.in",
    "requirements-dev.in",
    "requirements-test.in",
    "requirements-prod.in",
    "dev-requirements.in",
    "test-requirements.in",
    "prod-requirements.in",
    "constraints.in",
)
PIPTOOLS_IN_PATTERN = re.compile(r"^requirements(?:[-_.][\w.-]+)?\.in$", re.IGNORECASE)
PIPTOOLS_PYPROJECT_NAMES = ("pyproject.toml",)
PIPCOMPILE_HEADER_PATTERN = re.compile(
    r"(?:pip-compile|autogenerated by pip-compile|#.*pip-tools)",
    re.IGNORECASE,
)
PIPTOOLS_MARKER_PATTERN = re.compile(
    r"(?:^\[tool\.pip-tools\]|^\[tool\.pip-tools\.|pip-compile\s|pip-sync\s)",
    re.IGNORECASE | re.MULTILINE,
)
HARDCODED_SECRET_PATTERN = re.compile(
    r"(?:password|passwd|secret|api[_-]?key|token|credential|access[_-]?key|"
    r"private[_-]?key|client[_-]?secret|pypi[_-]?token|http-basic)\s*[=:]\s*"
    r"[\"']?[^\"'\s${}][^\"'<]*[\"']?",
    re.IGNORECASE,
)
PYPI_TOKEN_PATTERN = re.compile(r"[\"']?pypi-[A-Za-z0-9_-]{20,}[\"']?", re.IGNORECASE)
AWS_ACCESS_KEY_PATTERN = re.compile(r"[\"']?AKIA[0-9A-Z]{16}[\"']?", re.IGNORECASE)
INSECURE_HTTP_PATTERN = re.compile(
    r"http://(?!localhost|127\.0\.0\.1)[^\s\"'<>]+",
    re.IGNORECASE,
)
SCM_CREDENTIALS_PATTERN = re.compile(
    r"(?:git\+https?://|https?://)[^:@\s]+:[^@\s]+@",
    re.IGNORECASE,
)
DYNAMIC_VERSION_PATTERN = re.compile(
    r"(?:==\s*[\"']?\*[\"']?|[=<>!~]+\s*[\"']?\*[\"']?|"
    r"[=<>!~]+\s*[\"']?latest[\"']?|"
    r"(?<![=<>!~])>=\s*[\"']?\d|(?<![=<>!~])<=\s*[\"']?\d|"
    r"(?<![=<>!~])>\s*[\"']?\d|(?<![=<>!~])<\s*[\"']?\d)",
    re.IGNORECASE,
)
GIT_DEP_UNPINNED_PATTERN = re.compile(
    r"(?:@main\b|@master\b|@HEAD\b|@develop\b|#egg=[^&]+@main\b|branch=main\b|branch=master\b)",
    re.IGNORECASE,
)
CURL_PIPE_SHELL_PATTERN = re.compile(
    r"(?:curl|wget)\s+[^\n|]*\|\s*(?:ba)?sh\b",
    re.IGNORECASE,
)
INSECURE_SSL_PATTERN = re.compile(
    r"(?:cert\s*=\s*false|disable[_-]?ssl|ssl[_-]?verify\s*=\s*false|"
    r"trusted-host\s*=|cert\s*=\s*/dev/null)",
    re.IGNORECASE,
)
SENSITIVE_PATH_PATTERN = re.compile(
    r"(?:\.ssh/|\.aws/|/etc/passwd|/etc/shadow|\.kube/config)",
    re.IGNORECASE,
)
TRUSTED_HOST_PATTERN = re.compile(
    r"(?:--trusted-host|trusted-host)\s*[= ]?\s*([^\s#]+)",
    re.IGNORECASE,
)
INDEX_URL_PATTERN = re.compile(
    r"(?:--index-url|--extra-index-url|index-url|extra-index-url)\s*[= ]?\s*(\S+)",
    re.IGNORECASE,
)
ALLOW_UNSAFE_PATTERN = re.compile(r"--allow-unsafe\b", re.IGNORECASE)
EMIT_INDEX_URL_PATTERN = re.compile(r"--emit-index-url\b", re.IGNORECASE)
UNPINNED_REQUIREMENT_PATTERN = re.compile(
    r"^[a-zA-Z0-9][a-zA-Z0-9._-]*(?:\[[^\]]+\])?\s*$",
)


@dataclass
class PipToolsFinding:
    """A security or best-practice issue in a pip-tools configuration file."""

    kind: str
    severity: str
    message: str
    path: str
    lineno: int
    line: str = ""

    def format(self) -> str:
        """Return a single-line description."""
        return f"[{self.severity}] {self.path}:{self.lineno} — {self.message}"


@dataclass
class PipToolsInfo:
    """Parsed metadata about a pip-tools configuration file."""

    path: str
    lines: int = 0
    file_kind: str = ""
    dependencies: list[str] = field(default_factory=list)
    index_urls: list[str] = field(default_factory=list)


@dataclass
class PipToolsStats:
    """Aggregate pip-tools analysis statistics."""

    configs: int = 0
    files: int = 0
    findings: int = 0
    high_severity: int = 0
    medium_severity: int = 0
    low_severity: int = 0


def _has_pipcompile_header(path: Path) -> bool:
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:2048]
        return bool(PIPCOMPILE_HEADER_PATTERN.search(head))
    except OSError:
        return False


def _compiled_output_for_in(in_path: Path) -> Path | None:
    """Map requirements.in to its expected compiled requirements.txt sibling."""
    name = in_path.name
    if name.endswith(".in"):
        compiled_name = name[:-3] + ".txt"
        compiled = in_path.parent / compiled_name
        if compiled.exists():
            return compiled
    return None


def _is_piptools_file(path: Path) -> bool:
    """Return True if the path looks like a pip-tools configuration file."""
    name = path.name
    if name in PIPTOOLS_IN_NAMES or PIPTOOLS_IN_PATTERN.match(name):
        return True
    if name in PIPTOOLS_PYPROJECT_NAMES:
        try:
            head = path.read_text(encoding="utf-8", errors="replace")[:8192]
            if PIPTOOLS_MARKER_PATTERN.search(head):
                return True
        except OSError:
            pass
    if name.endswith(".txt") and _has_pipcompile_header(path):
        return True
    return False


def _file_kind(path: Path) -> str:
    name = path.name.lower()
    if name.endswith(".in"):
        return "requirements_in"
    if name == "pyproject.toml":
        return "pyproject"
    if name.endswith(".txt"):
        return "compiled_requirements"
    return "unknown"


class PipToolsAnalyzer:
    """Audit pip-tools configuration for security issues.

    Scans requirements.in, pip-compile output (requirements.txt), and
    pyproject.toml [tool.pip-tools] for hardcoded PyPI tokens, insecure HTTP
    index URLs, credentials in git/source URLs, unpinned compiled dependencies,
    --allow-unsafe and --emit-index-url flags, trusted-host bypasses, missing
    compiled lockfiles, and curl-pipe-to-shell in compile scripts.
    """

    def __init__(self, root: str) -> None:
        self.root = Path(root)
        self._findings: list[PipToolsFinding] | None = None
        self._stats: PipToolsStats | None = None
        self._infos: list[PipToolsInfo] | None = None

    def configs(self) -> list[Path]:
        """Return pip-tools configuration paths found in the project."""
        found: list[Path] = []
        for path in sorted(self.root.rglob("*")):
            if path.is_file() and _is_piptools_file(path):
                found.append(path)
        return found

    def _analyze_line(
        self,
        line: str,
        lineno: int,
        rel: str,
        *,
        is_compiled: bool,
    ) -> list[PipToolsFinding]:
        findings: list[PipToolsFinding] = []
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            return findings

        if HARDCODED_SECRET_PATTERN.search(line):
            findings.append(
                PipToolsFinding(
                    kind="hardcoded_secret",
                    severity="high",
                    message="hardcoded secret in pip-tools config — use PIP_INDEX_URL or CI secret stores",
                    path=rel,
                    lineno=lineno,
                    line=line,
                )
            )

        if PYPI_TOKEN_PATTERN.search(line):
            findings.append(
                PipToolsFinding(
                    kind="pypi_token",
                    severity="high",
                    message="PyPI token in pip-tools config — use env vars or keyring",
                    path=rel,
                    lineno=lineno,
                    line=line,
                )
            )

        if AWS_ACCESS_KEY_PATTERN.search(line):
            findings.append(
                PipToolsFinding(
                    kind="aws_access_key",
                    severity="high",
                    message="AWS access key in pip-tools config — use credential helpers or secret stores",
                    path=rel,
                    lineno=lineno,
                    line=line,
                )
            )

        if INSECURE_HTTP_PATTERN.search(line):
            findings.append(
                PipToolsFinding(
                    kind="insecure_http",
                    severity="medium",
                    message="insecure HTTP URL — use HTTPS for PyPI indexes and custom sources",
                    path=rel,
                    lineno=lineno,
                    line=line,
                )
            )

        if SCM_CREDENTIALS_PATTERN.search(line):
            findings.append(
                PipToolsFinding(
                    kind="scm_credentials",
                    severity="high",
                    message="credentials embedded in repository URL — use token env vars or SSH keys",
                    path=rel,
                    lineno=lineno,
                    line=line,
                )
            )

        if is_compiled and DYNAMIC_VERSION_PATTERN.search(stripped):
            dep_match = re.match(
                r"^([a-zA-Z0-9][a-zA-Z0-9._-]*)(?:\[[^\]]+\])?",
                stripped,
            )
            if dep_match and not stripped.startswith("-"):
                findings.append(
                    PipToolsFinding(
                        kind="unpinned_compiled_dep",
                        severity="medium",
                        message="unpinned dependency in compiled output — re-run pip-compile to pin with ==",
                        path=rel,
                        lineno=lineno,
                        line=line,
                    )
                )

        if GIT_DEP_UNPINNED_PATTERN.search(line):
            findings.append(
                PipToolsFinding(
                    kind="unpinned_git_dep",
                    severity="medium",
                    message="git dependency pinned to moving branch — pin to tag or commit SHA",
                    path=rel,
                    lineno=lineno,
                    line=line,
                )
            )

        if INSECURE_SSL_PATTERN.search(line):
            findings.append(
                PipToolsFinding(
                    kind="insecure_ssl",
                    severity="high",
                    message="SSL/TLS verification disabled — keep certificate validation enabled",
                    path=rel,
                    lineno=lineno,
                    line=line,
                )
            )

        if TRUSTED_HOST_PATTERN.search(line):
            findings.append(
                PipToolsFinding(
                    kind="trusted_host",
                    severity="medium",
                    message="trusted-host bypass — avoid disabling TLS hostname verification",
                    path=rel,
                    lineno=lineno,
                    line=line,
                )
            )

        if ALLOW_UNSAFE_PATTERN.search(line):
            findings.append(
                PipToolsFinding(
                    kind="allow_unsafe",
                    severity="medium",
                    message="--allow-unsafe enabled — review setuptools/pip/wheel pins before deploying",
                    path=rel,
                    lineno=lineno,
                    line=line,
                )
            )

        if EMIT_INDEX_URL_PATTERN.search(line):
            findings.append(
                PipToolsFinding(
                    kind="emit_index_url",
                    severity="low",
                    message="--emit-index-url embeds index URLs in compiled output — prefer env-based indexes",
                    path=rel,
                    lineno=lineno,
                    line=line,
                )
            )

        if CURL_PIPE_SHELL_PATTERN.search(line):
            findings.append(
                PipToolsFinding(
                    kind="curl_pipe_shell",
                    severity="high",
                    message="curl/wget piped to shell in pip-tools config — vendor scripts with checksum verification",
                    path=rel,
                    lineno=lineno,
                    line=line,
                )
            )

        if SENSITIVE_PATH_PATTERN.search(line):
            findings.append(
                PipToolsFinding(
                    kind="sensitive_path",
                    severity="high",
                    message="sensitive host path reference — avoid bundling credentials in builds",
                    path=rel,
                    lineno=lineno,
                    line=line,
                )
            )

        if is_compiled and UNPINNED_REQUIREMENT_PATTERN.match(stripped):
            findings.append(
                PipToolsFinding(
                    kind="unpinned_compiled_dep",
                    severity="medium",
                    message="unpinned dependency in compiled output — re-run pip-compile to pin with ==",
                    path=rel,
                    lineno=lineno,
                    line=line,
                )
            )

        return findings

    def _analyze_file(self, path: Path) -> tuple[list[PipToolsFinding], PipToolsInfo]:
        findings: list[PipToolsFinding] = []
        rel = str(path.relative_to(self.root))
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            return findings, PipToolsInfo(path=rel)

        raw_lines = text.splitlines()
        file_kind = _file_kind(path)
        is_compiled = file_kind == "compiled_requirements"
        info = PipToolsInfo(path=rel, lines=len(raw_lines), file_kind=file_kind)

        for lineno, line in enumerate(raw_lines, start=1):
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue

            index_match = INDEX_URL_PATTERN.search(stripped)
            if index_match:
                info.index_urls.append(index_match.group(1))

            dep_match = re.match(
                r"^([a-zA-Z0-9][a-zA-Z0-9._-]*)(?:\[[^\]]+\])?(?:\s*[=<>!~]+|\s*$)",
                stripped,
            )
            if dep_match and not stripped.startswith("-"):
                dep_name = dep_match.group(1)
                if dep_name.lower() not in ("index-url", "extra-index-url", "trusted-host"):
                    info.dependencies.append(dep_name)

            findings.extend(
                self._analyze_line(line, lineno, rel, is_compiled=is_compiled)
            )

        if file_kind == "requirements_in":
            compiled = _compiled_output_for_in(path)
            if compiled is None:
                findings.append(
                    PipToolsFinding(
                        kind="missing_compiled_output",
                        severity="low",
                        message="compiled requirements.txt missing — run pip-compile and commit the lockfile",
                        path=rel,
                        lineno=1,
                        line="",
                    )
                )

        return findings, info

    def analyze(self) -> list[PipToolsFinding]:
        """Run analysis and return all findings."""
        if self._findings is not None:
            return self._findings

        findings: list[PipToolsFinding] = []
        infos: list[PipToolsInfo] = []
        paths = self.configs()

        for path in paths:
            file_findings, info = self._analyze_file(path)
            findings.extend(file_findings)
            infos.append(info)

        high = sum(1 for f in findings if f.severity == "high")
        medium = sum(1 for f in findings if f.severity == "medium")
        low = sum(1 for f in findings if f.severity == "low")
        self._findings = findings
        self._infos = infos
        self._stats = PipToolsStats(
            configs=len(paths),
            files=len(paths),
            findings=len(findings),
            high_severity=high,
            medium_severity=medium,
            low_severity=low,
        )
        return findings

    @property
    def stats(self) -> PipToolsStats:
        """Return aggregate statistics."""
        if self._stats is None:
            self.analyze()
        return self._stats  # type: ignore[return-value]

    @property
    def infos(self) -> list[PipToolsInfo]:
        """Return parsed config metadata."""
        if self._infos is None:
            self.analyze()
        return self._infos  # type: ignore[return-value]

    def health_score(self) -> float:
        """Return a 0-100 health score (100 = no issues or no configs)."""
        self.analyze()
        stats = self.stats
        if stats.configs == 0:
            return 100.0
        if stats.findings == 0:
            return 100.0
        penalty = (
            stats.high_severity * 20.0
            + stats.medium_severity * 8.0
            + stats.low_severity * 2.0
        )
        return round(max(0.0, min(100.0, 100.0 - penalty)), 1)

    def generate_hardened_config(self) -> str:
        """Scaffold a hardened pip-tools workflow snippet with secure defaults."""
        return """\
# requirements.in — source dependencies for pip-compile
# Run: pip-compile --generate-hashes --output-file=requirements.txt requirements.in
# Never commit tokens in .in files — use PIP_INDEX_URL or CI secrets

requests>=2.31.0
flask>=3.0.0

# pyproject.toml [tool.pip-tools] (optional)
# [tool.pip-tools]
# compile-args = ["--generate-hashes"]
# Avoid --allow-unsafe unless setuptools/pip pins are reviewed
# Avoid --emit-index-url — configure indexes via environment variables
"""

    def summary(self) -> str:
        """Return a human-readable summary."""
        self.analyze()
        stats = self.stats
        if stats.configs == 0:
            return "Pip-tools configs: none found"
        return (
            f"Pip-tools configs: {stats.configs} config(s), "
            f"{stats.findings} finding(s) "
            f"({stats.high_severity} high, {stats.medium_severity} medium, {stats.low_severity} low)"
        )

    def to_context(self) -> str:
        """Format analysis as LLM-ready context."""
        self.analyze()
        stats = self.stats
        lines = [
            "Pip-tools analysis:",
            f"  configs: {stats.configs}",
            f"  findings: {stats.findings}",
            f"  health score: {self.health_score()}/100",
        ]
        for info in self.infos:
            deps = ", ".join(info.dependencies[:8]) if info.dependencies else "none"
            indexes = ", ".join(info.index_urls[:8]) if info.index_urls else "none"
            lines.append(
                f"  - {info.path} ({info.file_kind}): "
                f"{len(info.dependencies)} dependency(ies), {len(info.index_urls)} index URL(s)"
            )
            lines.append(f"    dependencies: {deps}")
            lines.append(f"    index URLs: {indexes}")
        for finding in (self._findings or [])[:25]:
            lines.append(f"  {finding.format()}")
        if self._findings and len(self._findings) > 25:
            lines.append(f"  ... and {len(self._findings) - 25} more finding(s)")
        return "\n".join(lines)
